

seed: 1212
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/MFA_NEW/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
data_folder: data

aug: False
max_frames: 200
eval_frames: 0
num_eval: 10
train_data_path: !ref <data_folder>/train/DB
val_data_path: !ref <data_folder>/val/DB
train_file: !ref <data_folder>/train.txt
test_file: !ref <data_folder>/test.txt
eval_file: !ref <data_folder>/eval.txt
musan_path: !ref <data_folder>/musan
rir_path: !ref  <data_folder>/RIRS_NOISES/simulated_rirs
eval_model_path: results/ecapa_tdnn/1212/save/ECAPA_TDNN_4.pt

#model parameters
C: 512
n_class: 2656
m: 0.2
s: 30
device: cuda

# Training parameters
num_epoch: 100
batch_size: 32
lr: 0.0005
lr_decay: 0.97
weight_decay: 2e-5 

sample_rate: 8000
shuffle: True
random_chunk: True
eval_interval: 1
fbankaug: True

dataset_options:
    aug: !ref <aug>
    eval_frames: !ref <eval_frames>
    num_eval: !ref <num_eval>
    max_frames: !ref <max_frames>
    train_file: !ref <train_file>
    test_file:  !ref <eval_file>
    musan_path: !ref <musan_path>
    rir_path: !ref <rir_path>


dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: !ref <shuffle>
    num_workers: 22
model_options:
    C: !ref <C>
    n_class: !ref <n_class>
    m: !ref <m>
    s: !ref <s>
    device: !ref <device>